#Raising an exception

raise ValueError("This is an example of a raised exception.")
